import type { Recipe, Category, Ingredient, Step, Tag } from "./types";

// ─── Categories ───

export const mockCategories: Category[] = [
  {
    id: 1,
    name: "Recipes",
    slug: "recipes",
    description: "All our tested and perfected recipes",
    parentId: null,
    sortOrder: 0,
    createdAt: new Date("2024-01-01"),
    children: [
      {
        id: 10,
        name: "Pasta & Noodles",
        slug: "pasta-noodles",
        description: "Fresh and dried pasta dishes",
        parentId: 1,
        sortOrder: 0,
        createdAt: new Date("2024-01-01"),
      },
      {
        id: 11,
        name: "Soups & Stews",
        slug: "soups-stews",
        description: "Warming bowls for every season",
        parentId: 1,
        sortOrder: 1,
        createdAt: new Date("2024-01-01"),
      },
      {
        id: 12,
        name: "Salads",
        slug: "salads",
        description: "Fresh, vibrant salads",
        parentId: 1,
        sortOrder: 2,
        createdAt: new Date("2024-01-01"),
      },
      {
        id: 13,
        name: "Meat & Poultry",
        slug: "meat-poultry",
        description: "From weeknight chicken to weekend roasts",
        parentId: 1,
        sortOrder: 3,
        createdAt: new Date("2024-01-01"),
      },
      {
        id: 14,
        name: "Seafood",
        slug: "seafood",
        description: "Fish, shellfish, and more",
        parentId: 1,
        sortOrder: 4,
        createdAt: new Date("2024-01-01"),
      },
      {
        id: 15,
        name: "Vegetarian",
        slug: "vegetarian",
        description: "Plant-forward mains and sides",
        parentId: 1,
        sortOrder: 5,
        createdAt: new Date("2024-01-01"),
      },
      {
        id: 16,
        name: "Baking & Desserts",
        slug: "baking-desserts",
        description: "Sweet treats and breads",
        parentId: 1,
        sortOrder: 6,
        createdAt: new Date("2024-01-01"),
      },
      {
        id: 17,
        name: "Breakfast & Brunch",
        slug: "breakfast-brunch",
        description: "Start the day right",
        parentId: 1,
        sortOrder: 7,
        createdAt: new Date("2024-01-01"),
      },
    ],
  },
  {
    id: 2,
    name: "Techniques",
    slug: "techniques",
    description: "Master the fundamentals",
    parentId: null,
    sortOrder: 1,
    createdAt: new Date("2024-01-01"),
    children: [
      {
        id: 20,
        name: "Knife Skills",
        slug: "knife-skills",
        description: "Cut like a pro",
        parentId: 2,
        sortOrder: 0,
        createdAt: new Date("2024-01-01"),
      },
      {
        id: 21,
        name: "Grilling",
        slug: "grilling",
        description: "Fire and smoke",
        parentId: 2,
        sortOrder: 1,
        createdAt: new Date("2024-01-01"),
      },
      {
        id: 22,
        name: "Baking Basics",
        slug: "baking-basics",
        description: "Flour, water, heat, patience",
        parentId: 2,
        sortOrder: 2,
        createdAt: new Date("2024-01-01"),
      },
      {
        id: 23,
        name: "Fermentation",
        slug: "fermentation",
        description: "The art of patience",
        parentId: 2,
        sortOrder: 3,
        createdAt: new Date("2024-01-01"),
      },
    ],
  },
  {
    id: 3,
    name: "Equipment",
    slug: "equipment",
    description: "Reviews and recommendations",
    parentId: null,
    sortOrder: 2,
    createdAt: new Date("2024-01-01"),
    children: [
      {
        id: 30,
        name: "Cookware",
        slug: "cookware",
        description: "Pans, pots, and Dutch ovens",
        parentId: 3,
        sortOrder: 0,
        createdAt: new Date("2024-01-01"),
      },
      {
        id: 31,
        name: "Knives",
        slug: "knives",
        description: "The most important tool",
        parentId: 3,
        sortOrder: 1,
        createdAt: new Date("2024-01-01"),
      },
      {
        id: 32,
        name: "Small Appliances",
        slug: "small-appliances",
        description: "Blenders, toasters, and more",
        parentId: 3,
        sortOrder: 2,
        createdAt: new Date("2024-01-01"),
      },
    ],
  },
  {
    id: 4,
    name: "Ingredients",
    slug: "ingredients",
    description: "Deep dives into what we cook with",
    parentId: null,
    sortOrder: 3,
    createdAt: new Date("2024-01-01"),
    children: [
      {
        id: 40,
        name: "Pantry Staples",
        slug: "pantry-staples",
        description: "Oils, vinegars, spices",
        parentId: 4,
        sortOrder: 0,
        createdAt: new Date("2024-01-01"),
      },
      {
        id: 41,
        name: "Seasonal Produce",
        slug: "seasonal-produce",
        description: "What's fresh right now",
        parentId: 4,
        sortOrder: 1,
        createdAt: new Date("2024-01-01"),
      },
    ],
  },
  {
    id: 5,
    name: "Holidays",
    slug: "holidays",
    description: "Seasonal menus and celebrations",
    parentId: null,
    sortOrder: 4,
    createdAt: new Date("2024-01-01"),
    children: [
      {
        id: 50,
        name: "Thanksgiving",
        slug: "thanksgiving",
        description: "The biggest meal of the year",
        parentId: 5,
        sortOrder: 0,
        createdAt: new Date("2024-01-01"),
      },
      {
        id: 51,
        name: "Christmas",
        slug: "christmas",
        description: "Festive feasts",
        parentId: 5,
        sortOrder: 1,
        createdAt: new Date("2024-01-01"),
      },
      {
        id: 52,
        name: "Summer Cookout",
        slug: "summer-cookout",
        description: "Fire up the grill",
        parentId: 5,
        sortOrder: 2,
        createdAt: new Date("2024-01-01"),
      },
    ],
  },
  {
    id: 6,
    name: "About",
    slug: "about",
    description: "Our story",
    parentId: null,
    sortOrder: 5,
    createdAt: new Date("2024-01-01"),
  },
];

// ─── Tags ───

export const mockTags: Tag[] = [
  { id: 1, name: "Quick & Easy", slug: "quick-easy" },
  { id: 2, name: "One-Pot", slug: "one-pot" },
  { id: 3, name: "Make Ahead", slug: "make-ahead" },
  { id: 4, name: "Gluten-Free", slug: "gluten-free" },
  { id: 5, name: "Dairy-Free", slug: "dairy-free" },
  { id: 6, name: "Comfort Food", slug: "comfort-food" },
  { id: 7, name: "Date Night", slug: "date-night" },
  { id: 8, name: "Meal Prep", slug: "meal-prep" },
  { id: 9, name: "Budget Friendly", slug: "budget-friendly" },
  { id: 10, name: "Kid Friendly", slug: "kid-friendly" },
];

// ─── Recipes ───

const baseIngredients: Record<string, Ingredient[]> = {
  "crispy-pan-seared-salmon": [
    { id: 1, recipeId: 1, groupName: null, name: "skin-on salmon fillets", quantity: 4, unitUs: "6-oz", unitMetric: "170-g", quantityMetric: 4, note: "about 1 inch thick", sortOrder: 0 },
    { id: 2, recipeId: 1, groupName: null, name: "kosher salt", quantity: 1, unitUs: "tsp", unitMetric: "tsp", quantityMetric: 1, note: null, sortOrder: 1 },
    { id: 3, recipeId: 1, groupName: null, name: "freshly ground black pepper", quantity: 0.5, unitUs: "tsp", unitMetric: "tsp", quantityMetric: 0.5, note: null, sortOrder: 2 },
    { id: 4, recipeId: 1, groupName: null, name: "vegetable oil", quantity: 2, unitUs: "tbsp", unitMetric: "ml", quantityMetric: 30, note: "high smoke point", sortOrder: 3 },
    { id: 5, recipeId: 1, groupName: null, name: "unsalted butter", quantity: 2, unitUs: "tbsp", unitMetric: "g", quantityMetric: 28, note: null, sortOrder: 4 },
    { id: 6, recipeId: 1, groupName: null, name: "garlic cloves", quantity: 3, unitUs: "cloves", unitMetric: "cloves", quantityMetric: 3, note: "smashed", sortOrder: 5 },
    { id: 7, recipeId: 1, groupName: null, name: "fresh thyme sprigs", quantity: 4, unitUs: "sprigs", unitMetric: "sprigs", quantityMetric: 4, note: null, sortOrder: 6 },
    { id: 8, recipeId: 1, groupName: null, name: "lemon", quantity: 1, unitUs: "whole", unitMetric: "whole", quantityMetric: 1, note: "halved", sortOrder: 7 },
    { id: 9, recipeId: 1, groupName: "Herb Sauce", name: "fresh dill", quantity: 0.25, unitUs: "cup", unitMetric: "g", quantityMetric: 15, note: "chopped", sortOrder: 8 },
    { id: 10, recipeId: 1, groupName: "Herb Sauce", name: "capers", quantity: 1, unitUs: "tbsp", unitMetric: "tbsp", quantityMetric: 1, note: "drained", sortOrder: 9 },
    { id: 11, recipeId: 1, groupName: "Herb Sauce", name: "extra-virgin olive oil", quantity: 3, unitUs: "tbsp", unitMetric: "ml", quantityMetric: 45, note: null, sortOrder: 10 },
  ],
  "slow-roasted-tomato-soup": [
    { id: 20, recipeId: 2, groupName: null, name: "Roma tomatoes", quantity: 3, unitUs: "lbs", unitMetric: "kg", quantityMetric: 1.4, note: "halved", sortOrder: 0 },
    { id: 21, recipeId: 2, groupName: null, name: "yellow onion", quantity: 1, unitUs: "large", unitMetric: "large", quantityMetric: 1, note: "quartered", sortOrder: 1 },
    { id: 22, recipeId: 2, groupName: null, name: "garlic head", quantity: 1, unitUs: "whole", unitMetric: "whole", quantityMetric: 1, note: "top sliced off", sortOrder: 2 },
    { id: 23, recipeId: 2, groupName: null, name: "olive oil", quantity: 3, unitUs: "tbsp", unitMetric: "ml", quantityMetric: 45, note: null, sortOrder: 3 },
    { id: 24, recipeId: 2, groupName: null, name: "chicken or vegetable stock", quantity: 2, unitUs: "cups", unitMetric: "ml", quantityMetric: 480, note: null, sortOrder: 4 },
    { id: 25, recipeId: 2, groupName: null, name: "heavy cream", quantity: 0.5, unitUs: "cup", unitMetric: "ml", quantityMetric: 120, note: "optional", sortOrder: 5 },
    { id: 26, recipeId: 2, groupName: null, name: "fresh basil", quantity: 0.25, unitUs: "cup", unitMetric: "g", quantityMetric: 10, note: "torn", sortOrder: 6 },
  ],
};

const baseSteps: Record<string, Step[]> = {
  "crispy-pan-seared-salmon": [
    { id: 1, recipeId: 1, stepNumber: 1, instruction: "Pat salmon fillets completely dry with paper towels. This is the most important step for crispy skin. Season generously on both sides with salt and pepper. Let sit at room temperature for 15 minutes.", imageUrl: null, tip: "Moisture is the enemy of crispy skin. Really press those paper towels into the fish." },
    { id: 2, recipeId: 1, stepNumber: 2, instruction: "Heat vegetable oil in a large stainless steel or cast-iron skillet over medium-high heat until the oil just begins to smoke. You should see wisps rising from the surface.", imageUrl: null, tip: "Don't use nonstick — you need the heat of stainless steel or cast iron for proper crisping." },
    { id: 3, recipeId: 1, stepNumber: 3, instruction: "Carefully lay salmon fillets skin-side down in the pan, pressing gently with a spatula for the first 30 seconds to prevent curling. Cook without moving for 4 minutes until the skin is deeply golden and releases easily from the pan.", imageUrl: null, tip: "Resist the urge to peek! If the fish sticks, it's not ready to flip." },
    { id: 4, recipeId: 1, stepNumber: 4, instruction: "Reduce heat to medium. Add butter, garlic, and thyme to the pan. Once the butter foams, tilt the pan slightly and use a spoon to baste the salmon with the infused butter for 1–2 minutes.", imageUrl: null, tip: null },
    { id: 5, recipeId: 1, stepNumber: 5, instruction: "Flip fillets and cook for just 1 more minute for medium-rare (the center should still be slightly translucent). Squeeze lemon over the top. Transfer to plates and spoon the herb sauce alongside.", imageUrl: null, tip: "For medium, cook 2 minutes after flipping. Salmon continues to cook as it rests." },
  ],
  "slow-roasted-tomato-soup": [
    { id: 10, recipeId: 2, stepNumber: 1, instruction: "Preheat oven to 325°F (160°C). Arrange tomato halves cut-side up on a large rimmed baking sheet. Nestle onion quarters and garlic head among the tomatoes. Drizzle everything with olive oil, season with salt and pepper.", imageUrl: null, tip: null },
    { id: 11, recipeId: 2, stepNumber: 2, instruction: "Roast for 2 hours until tomatoes are deeply caramelized and collapsed. The edges should be dark and jammy. This slow roast concentrates flavor like nothing else.", imageUrl: null, tip: "Low and slow is the secret. Don't rush this step." },
    { id: 12, recipeId: 2, stepNumber: 3, instruction: "Squeeze roasted garlic from the skin into a blender. Add roasted tomatoes, onions, and any juices from the pan. Add stock and blend until silky smooth. Season to taste.", imageUrl: null, tip: null },
    { id: 13, recipeId: 2, stepNumber: 4, instruction: "Transfer to a pot over medium heat. Stir in cream if using. Simmer gently for 5 minutes. Ladle into bowls and finish with torn basil, a drizzle of olive oil, and crusty bread.", imageUrl: null, tip: "For a vegan version, swirl in coconut cream or cashew cream instead." },
  ],
};

export const mockRecipes: Recipe[] = [
  {
    id: 1,
    title: "Crispy Pan-Seared Salmon with Herb Sauce",
    slug: "crispy-pan-seared-salmon",
    description: "Restaurant-quality crispy-skinned salmon in under 20 minutes. The key is a screaming-hot pan and bone-dry fish.",
    introHtml: `<p>There's a reason crispy-skinned salmon is on every restaurant menu — when done right, the contrast between shattering-crisp skin and buttery, barely-set flesh is one of the great pleasures of cooking.</p><p>The technique is simple but unforgiving: your fish must be dry, your pan must be hot, and you must not touch it. That's it. Master those three things and you'll never order salmon out again.</p><p>We finish this with a quick herb sauce — dill, capers, good olive oil — that cuts through the richness and makes the whole thing sing.</p>`,
    heroImage: null,
    heroVideo: null,
    prepTime: 10,
    cookTime: 8,
    restTime: null,
    servings: 4,
    difficulty: "easy",
    published: true,
    featured: true,
    categoryId: 14,
    createdAt: new Date("2024-12-15"),
    updatedAt: new Date("2024-12-15"),
    category: { id: 14, name: "Seafood", slug: "seafood", description: "Fish, shellfish, and more", parentId: 1, sortOrder: 4, createdAt: new Date("2024-01-01") },
    ingredients: baseIngredients["crispy-pan-seared-salmon"],
    steps: baseSteps["crispy-pan-seared-salmon"],
    tags: [mockTags[0], mockTags[6]],
    reviewStats: { averageRating: 4.8, totalReviews: 127 },
  },
  {
    id: 2,
    title: "Slow-Roasted Tomato Soup",
    slug: "slow-roasted-tomato-soup",
    description: "Two hours in a low oven transforms ordinary tomatoes into something extraordinary. This is the tomato soup to end all tomato soups.",
    introHtml: `<p>Most tomato soup recipes are a letdown — thin, acidic, tasting more of the can than the garden. This one is different.</p><p>By slow-roasting Roma tomatoes at a low temperature for two hours, we concentrate their sweetness and develop deep, complex caramelization that no amount of stovetop cooking can replicate.</p>`,
    heroImage: null,
    heroVideo: null,
    prepTime: 15,
    cookTime: 135,
    restTime: null,
    servings: 6,
    difficulty: "easy",
    published: true,
    featured: true,
    categoryId: 11,
    createdAt: new Date("2024-12-10"),
    updatedAt: new Date("2024-12-10"),
    category: { id: 11, name: "Soups & Stews", slug: "soups-stews", description: null, parentId: 1, sortOrder: 1, createdAt: new Date("2024-01-01") },
    ingredients: baseIngredients["slow-roasted-tomato-soup"],
    steps: baseSteps["slow-roasted-tomato-soup"],
    tags: [mockTags[1], mockTags[5], mockTags[4]],
    reviewStats: { averageRating: 4.9, totalReviews: 203 },
  },
  {
    id: 3,
    title: "The Ultimate Smash Burger",
    slug: "ultimate-smash-burger",
    description: "Thin, lacy-edged, impossibly crispy. This diner-style smash burger has more flavor per square inch than any thick pub patty.",
    introHtml: null,
    heroImage: null,
    heroVideo: null,
    prepTime: 10,
    cookTime: 6,
    restTime: 5,
    servings: 4,
    difficulty: "easy",
    published: true,
    featured: true,
    categoryId: 13,
    createdAt: new Date("2024-12-08"),
    updatedAt: new Date("2024-12-08"),
    category: { id: 13, name: "Meat & Poultry", slug: "meat-poultry", description: null, parentId: 1, sortOrder: 3, createdAt: new Date("2024-01-01") },
    tags: [mockTags[0], mockTags[5], mockTags[9]],
    reviewStats: { averageRating: 4.7, totalReviews: 89 },
  },
  {
    id: 4,
    title: "Cacio e Pepe",
    slug: "cacio-e-pepe",
    description: "Three ingredients. Infinite technique. The Roman classic that rewards practice and punishes shortcuts.",
    introHtml: null,
    heroImage: null,
    heroVideo: null,
    prepTime: 5,
    cookTime: 12,
    restTime: null,
    servings: 2,
    difficulty: "medium",
    published: true,
    featured: false,
    categoryId: 10,
    createdAt: new Date("2024-12-05"),
    updatedAt: new Date("2024-12-05"),
    category: { id: 10, name: "Pasta & Noodles", slug: "pasta-noodles", description: null, parentId: 1, sortOrder: 0, createdAt: new Date("2024-01-01") },
    tags: [mockTags[0], mockTags[6]],
    reviewStats: { averageRating: 4.6, totalReviews: 156 },
  },
  {
    id: 5,
    title: "Shakshuka with Feta and Herbs",
    slug: "shakshuka-feta-herbs",
    description: "Eggs poached in a spiced tomato sauce with crumbled feta — the ultimate one-pan brunch that feeds a crowd.",
    introHtml: null,
    heroImage: null,
    heroVideo: null,
    prepTime: 10,
    cookTime: 25,
    restTime: null,
    servings: 4,
    difficulty: "easy",
    published: true,
    featured: false,
    categoryId: 17,
    createdAt: new Date("2024-12-01"),
    updatedAt: new Date("2024-12-01"),
    category: { id: 17, name: "Breakfast & Brunch", slug: "breakfast-brunch", description: null, parentId: 1, sortOrder: 7, createdAt: new Date("2024-01-01") },
    tags: [mockTags[1], mockTags[4]],
    reviewStats: { averageRating: 4.5, totalReviews: 78 },
  },
  {
    id: 6,
    title: "Roasted Cauliflower with Tahini and Pomegranate",
    slug: "roasted-cauliflower-tahini",
    description: "A whole head of cauliflower, roasted until deeply golden, then drizzled with tahini and scattered with jewel-toned pomegranate seeds.",
    introHtml: null,
    heroImage: null,
    heroVideo: null,
    prepTime: 10,
    cookTime: 45,
    restTime: null,
    servings: 4,
    difficulty: "easy",
    published: true,
    featured: false,
    categoryId: 15,
    createdAt: new Date("2024-11-28"),
    updatedAt: new Date("2024-11-28"),
    category: { id: 15, name: "Vegetarian", slug: "vegetarian", description: null, parentId: 1, sortOrder: 5, createdAt: new Date("2024-01-01") },
    tags: [mockTags[3], mockTags[4], mockTags[14] ?? mockTags[5]],
    reviewStats: { averageRating: 4.4, totalReviews: 45 },
  },
  {
    id: 7,
    title: "Brown Butter Chocolate Chip Cookies",
    slug: "brown-butter-chocolate-chip-cookies",
    description: "Nutty brown butter, two kinds of chocolate, and a 24-hour rest make these the most deeply flavored cookies you'll ever bake.",
    introHtml: null,
    heroImage: null,
    heroVideo: null,
    prepTime: 20,
    cookTime: 12,
    restTime: 1440,
    servings: 24,
    difficulty: "medium",
    published: true,
    featured: false,
    categoryId: 16,
    createdAt: new Date("2024-11-25"),
    updatedAt: new Date("2024-11-25"),
    category: { id: 16, name: "Baking & Desserts", slug: "baking-desserts", description: null, parentId: 1, sortOrder: 6, createdAt: new Date("2024-01-01") },
    tags: [mockTags[2], mockTags[5]],
    reviewStats: { averageRating: 4.9, totalReviews: 312 },
  },
  {
    id: 8,
    title: "Thai Green Curry with Chicken",
    slug: "thai-green-curry-chicken",
    description: "Fragrant, spicy, and rich with coconut milk — better than takeout and ready in 30 minutes flat.",
    introHtml: null,
    heroImage: null,
    heroVideo: null,
    prepTime: 15,
    cookTime: 20,
    restTime: null,
    servings: 4,
    difficulty: "easy",
    published: true,
    featured: false,
    categoryId: 13,
    createdAt: new Date("2024-11-20"),
    updatedAt: new Date("2024-11-20"),
    category: { id: 13, name: "Meat & Poultry", slug: "meat-poultry", description: null, parentId: 1, sortOrder: 3, createdAt: new Date("2024-01-01") },
    tags: [mockTags[0], mockTags[4]],
    reviewStats: { averageRating: 4.6, totalReviews: 67 },
  },
  {
    id: 9,
    title: "Perfect Sourdough Boule",
    slug: "perfect-sourdough-boule",
    description: "A crusty, open-crumbed loaf with complex tang. Patience is the only special ingredient.",
    introHtml: null,
    heroImage: null,
    heroVideo: null,
    prepTime: 30,
    cookTime: 45,
    restTime: 720,
    servings: 1,
    difficulty: "hard",
    published: true,
    featured: false,
    categoryId: 16,
    createdAt: new Date("2024-11-15"),
    updatedAt: new Date("2024-11-15"),
    category: { id: 16, name: "Baking & Desserts", slug: "baking-desserts", description: null, parentId: 1, sortOrder: 6, createdAt: new Date("2024-01-01") },
    tags: [mockTags[2]],
    reviewStats: { averageRating: 4.3, totalReviews: 98 },
  },
];

// ─── Helpers ───

export function getMockFeaturedRecipes(): Recipe[] {
  return mockRecipes.filter((r) => r.featured);
}

export function getMockLatestRecipes(limit = 6): Recipe[] {
  return mockRecipes.slice(0, limit);
}

export function getMockRecipeBySlug(slug: string): Recipe | null {
  return mockRecipes.find((r) => r.slug === slug) ?? null;
}

export function getMockRecipesByCategory(categorySlug: string): Recipe[] {
  return mockRecipes.filter((r) => r.category?.slug === categorySlug);
}

export function getMockCategoryBySlug(slug: string): Category | null {
  for (const cat of mockCategories) {
    if (cat.slug === slug) return cat;
    if (cat.children) {
      const child = cat.children.find((c) => c.slug === slug);
      if (child) return child;
    }
  }
  return null;
}

export function searchMockRecipes(query: string): Recipe[] {
  const q = query.toLowerCase();
  return mockRecipes.filter(
    (r) =>
      r.title.toLowerCase().includes(q) ||
      r.description?.toLowerCase().includes(q) ||
      r.category?.name.toLowerCase().includes(q)
  );
}

// Hero placeholder colors keyed by recipe id — used when no heroImage
export const heroPlaceholderColors: Record<number, string> = {
  1: "#e8c4a0",
  2: "#c45d3e",
  3: "#d4a853",
  4: "#e8dcc8",
  5: "#c43e3e",
  6: "#d4c9a8",
  7: "#6b4226",
  8: "#4a7a3d",
  9: "#c4a46b",
};
